export const INIT_GOOGLE_SIGNIN = "INIT_GOOGLE_SIGNIN";
export const GOOGLE_INIT_SUCCESS = "GOOGLE_INIT_SUCCESS"
export const START_GOOGLE_SIGNIN = "START_GOOGLE_SIGNIN";
export const SUCCESS_GOOGLE_SIGNIN = "SUCCESS_GOOGLE_SIGNIN";
export const FAILED_GOOGLE_SIGNIN = "FAILED_GOOGLE_SIGNIN";
export const GET_FILES = "GET_FILES";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const ON_FOLDER_SELECTED = "ON_FOLDER_SELECTED";
export const GET_FILES_RESPONSE = "GET_FILES_RESPONSE";

export const CHECK_SIGNIN = "CHECK_SIGNIN";
export const SET_REDIRECT_URL = "SET_REDIRECT_URL";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const AUTHENTICATE_USER_RESPONSE = "AUTHENTICATE_USER_RESPONSE";

//folder actions
export const DELETE_FOLDER = "DELETE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";
